### ISSUE TITLE
Problem with package into darwin_arm64

### ISSUE THREAD

**Issue by qdupuy** [scaleway/terraform-provider-scaleway#1075]
Hello,

Overnight, without any modification on my side, I have the following error on the scaleway provider :

```
Initializing the backend...

Initializing provider plugins...
- Finding latest version of scaleway/scaleway...
- Finding latest version of hashicorp/template...
- Using previously-installed scaleway/scaleway v2.2.0
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
```

Terraform version :

```
terraform -v
Terraform v1.1.5
on darwin_arm64
```

**Comment by remyleone** [comment]
Hello, have you tried to upgrade to the latest version? Does this behavior still happen?

**Comment by qdupuy** [comment]
Hello,

Yes, still present

**Comment by remyleone** [comment]
Could you share the snippet of code that you have that exhibits this behavior? What machine do you run this code on?

**Comment by qdupuy** [comment]
Error :

```
Stack trace from the terraform-provider-scaleway_v2.2.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x10350241c]

goroutine 44 [running]:
github.com/scaleway/terraform-provider-scaleway/scaleway.resourceScalewayLbIPRead({0x103986568, 0x140007ac900}, 0x140007b0580, {0x1037f85a0, 0x1400051c9c0})
        github.com/scaleway/terraform-provider-scaleway/scaleway/resource_lb_ip.go:109 +0x36c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1400026cee0, {0x1039864f8, 0x140006b03c0}, 0x140007b0580, {0x1037f85a0, 0x1400051c9c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:358 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400026cee0, {0x1039864f8, 0x140006b03c0}, 0x140001e6820, {0x1037f85a0, 0x1400051c9c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x388
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140000988b8, {0x1039864f8, 0x140006b03c0}, 0x140006b0440)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x5f4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1400016e500, {0x1039865a0, 0x14000609800}, 0x140007ac2a0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x3ac
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x103926c80, 0x1400016e500}, {0x1039865a0, 0x14000609800}, 0x140007ac240, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000c28c0, {0x1039955c0, 0x1400055a180}, 0x14000296400, 0x140001f7bf0, 0x103fd3a90, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xc38
google.golang.org/grpc.(*Server).handleStream(0x140000c28c0, {0x1039955c0, 0x1400055a180}, 0x14000296400, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000290560, 0x140000c28c0, {0x1039955c0, 0x1400055a180}, 0x14000296400)
        google.golang.org/grpc@v1.32.0/server.go:859 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1f0

Error: The terraform-provider-scaleway_v2.2.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
I run terraform from my mac

**Comment by remyleone** [comment]
Also, I've just tried on an M1 and the basic snippet of code is working. Could you try sending me a minimal snippet of code that reproduces the behavior that you are experiencing? Having it will help me reproduce your bug and push a patch.
