### ISSUE TITLE
Crash on RDB permissions

### ISSUE THREAD

**Issue by Twister42** [scaleway/terraform-provider-scaleway#1140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.13.0
+ provider registry.terraform.io/fluxcd/flux v0.11.2
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.1
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/scaleway/scaleway v2.2.1-rc.1
```

### Affected Resource(s)

* scaleway_XXXX

### Terraform Configuration Files

```hcl
...
```
I'll try to make a simple configuration later

### Debug Output

Too many private stuff in it
I'll try to get a pruned output later

### Panic Output

None appart the stack

### Expected Behavior

not crashing

### Actual Behavior

```
Stack trace from the terraform-provider-scaleway_v2.2.1-rc.1 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 495 [running]:
github.com/scaleway/terraform-provider-scaleway/v2/scaleway.getDatabase({0x1169648, 0xc0014c8720}, 0xc0014c8720, {0xc000038580, 0x6}, {0xc000038587, 0x24}, {0xc0000385ac, 0x8})
	github.com/scaleway/terraform-provider-scaleway/v2/scaleway/resource_rdb_database.go:124 +0x205
github.com/scaleway/terraform-provider-scaleway/v2/scaleway.resourceScalewayRdbDatabaseRead({0x1169648, 0xc0014c8720}, 0xc00055cc80, {0xd71fa0, 0xc000417ee0})
	github.com/scaleway/terraform-provider-scaleway/v2/scaleway/resource_rdb_database.go:139 +0x2c6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00025ddc0, {0x11695d8, 0xc0007f7440}, 0x24, {0xd71fa0, 0xc000417ee0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:358 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00025ddc0, {0x11695d8, 0xc0007f7440}, 0xc0001bf930, {0xd71fa0, 0xc000417ee0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00028c8a0, {0x11695d8, 0xc0007f7440}, 0xc0007f74c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000128280, {0x1169680, 0xc0014c41b0}, 0xc0014c80c0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xea56e0, 0xc000128280}, {0x1169680, 0xc0014c41b0}, 0xc0014c8060, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a68c0, {0x1179a80, 0xc0000f8480}, 0xc000a98000, 0xc00021be00, 0x17e1b90, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0002a68c0, {0x1179a80, 0xc0000f8480}, 0xc000a98000, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-scaleway_v2.2.1-rc.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2022-03-14T13:43:27.827+0100 [DEBUG] provider: plugin exited
```

### Steps to Reproduce

1. use the rdb ressources
2. create a db
3. create users
4. grand privileges
5. edit users/privileges online 
6. terraform apply

### Important Factoids

Nothing

**Comment by remyleone** [comment]
Hello, thanks a lot for preparing a short version :). Will try to reproduce once I got it.

**Comment by Twister42** [comment]
The bug is quite simple to reproduce : 
```
resource "scaleway_rdb_instance" "pgsql" {
  name           = "bug"
  node_type      = "db-dev-m"
  engine         = "PostgreSQL-13"
  is_ha_cluster  = false
  disable_backup = true
  user_name      = "admin"
  password       = random_password.db_password.result
  tags           = ["bug"]
}

resource "random_password" "db_password" {
  length           = 17
  special          = true
  number           = true
  min_numeric      = 1
  min_special      = 1
  min_upper        = 1
  min_lower        = 1
  override_special = "$@\"'"
}

/** Dev **/
resource "random_password" "bug" {
  length           = 17
  special          = true
  number           = true
  min_numeric      = 1
  min_special      = 1
  min_upper        = 1
  min_lower        = 1
  override_special = "$@\"'"
}

resource "scaleway_rdb_user" "bug" {
  instance_id = scaleway_rdb_instance.pgsql.id
  name        = "bug"
  password    = random_password.bug.result
  is_admin    = false
}

resource "scaleway_rdb_database" "bug" {
  instance_id = scaleway_rdb_instance.pgsql.id
  name        = "bug"
}

resource "scaleway_rdb_privilege" "bug" {
  instance_id   = scaleway_rdb_instance.pgsql.id
  user_name     = "bug"
  database_name = "bug"
  permission    = "all"
}
```
Just apply this, delete the bug database, reapply.

**Comment by Twister42** [comment]
Btw there is another bug, when you apply this TF you an error on the first run : 
```Error: scaleway-sdk-go: invalid argument(s): database_name does not respect constraint, This database is not managed by RDB service, you can not change permission with the API. Use CLI instead
 ```

**Comment by remyleone** [comment]
Ok about the second problem. It is probably due to a race condition. Basically, terraform is trying to create a privilege before the database is created. Because terraform cannot guess that there is a dependency between the two and because the instance will not change status we cannot do a wait on it. Add a [`depends_on`](https://www.terraform.io/language/meta-arguments/depends_on) on the privilege resource like this:

```hcl
resource "scaleway_rdb_privilege" "bug" {
	instance_id   = scaleway_rdb_instance.pgsql.id
	user_name     = "bug"
	database_name = "bug"
	permission    = "all"

	depends_on = [scaleway_rdb_user.bug, scaleway_rdb_database.bug]
}
```

**Comment by Twister42** [comment]
Maybe the api could know that the instance and database are being created and the provider could poll until it's ready ?
The console can show the instance being there even if it's not ready.

**Comment by remyleone** [comment]
You cannot alter the database while the instance is not ready. Plus the instance status does not change while updating user or permission so we cannot poll on that. `depends_on` seems to be the most efficient way to do it for now. I've prepared a PR to update the documentation about it.
