### ISSUE TITLE
Error when updating Serverless Container `min_scale` or `max_scale` arguments

### ISSUE THREAD

**Issue by rclement** [scaleway/terraform-provider-scaleway#1434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash
$ terraform -version
Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/scaleway/scaleway v2.2.7
```

### Affected Resource(s)

* `scaleway_container`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    scaleway = {
      source  = "scaleway/scaleway"
      version = "=2.2.7"
    }
  }
}

provider "scaleway" {
}

resource "scaleway_container_namespace" "default" {
  name             = "test-ns"
  description      = "Test Container Namespace"
  destroy_registry = true
}

resource "scaleway_container" "default" {
  name         = "test-app"
  description  = "Test Container Application"
  namespace_id = scaleway_container_namespace.default.id
  port         = 5000
  min_scale    = 0
  max_scale    = 1
  privacy      = "private"
  deploy       = false
}
```

### Panic Output

```bash
scaleway_container.default: Modifying... [id=fr-par/2e6ffb94-2580-4880-9727-640f2be7d507]
╷
│ Error: Plugin did not respond
│ 
│   with scaleway_container.default,
│   on main.tf line 19, in resource "scaleway_container" "default":
│   19: resource "scaleway_container" "default" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-scaleway_v2.2.7 plugin:

panic: interface conversion: interface {} is int, not uint32

goroutine 67 [running]:
github.com/scaleway/terraform-provider-scaleway/v2/scaleway.toUint32(...)
        github.com/scaleway/terraform-provider-scaleway/v2/scaleway/helpers.go:621
github.com/scaleway/terraform-provider-scaleway/v2/scaleway.resourceScalewayContainerUpdate({0x1edfe68, 0xc0007ad320}, 0xc000749f80, {0x1a659a0, 0xc0006ff9b0})
        github.com/scaleway/terraform-provider-scaleway/v2/scaleway/resource_container.go:289 +0x1165
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0002cc380, {0x1edfea0, 0xc000544ff0}, 0xd, {0x1a659a0, 0xc0006ff9b0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002cc380, {0x1edfea0, 0xc000544ff0}, 0xc000743520, 0xc000749e00, {0x1a659a0, 0xc0006ff9b0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:847 +0x9e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000cae0, {0x1edfea0, 0xc000544e70}, 0xc0005109b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002dc280, {0x1edfea0, 0xc000544600}, 0xc0005203f0)
        github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/tf5server/server.go:813 +0x551
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1bb5840, 0xc0002dc280}, {0x1edfea0, 0xc000544600}, 0xc000520380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000292540, {0x1ef1a10, 0xc0005eb860}, 0xc000541200, 0xc0005c6e70, 0x25e3780, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb03
google.golang.org/grpc.(*Server).handleStream(0xc000292540, {0x1ef1a10, 0xc0005eb860}, 0xc000541200, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x294

Error: The terraform-provider-scaleway_v2.2.7 plugin crashed!
```

### Expected Behavior

`scaleway_container` instance is created and updated with new values for `min_scale` and `max_scale` for subsequent updates.

### Actual Behavior

`scaleway_container` instance is created with initial values for `min_scale` and `max_scale`. Subsequent updates are not applied as the Scaleway Terraform plugin is crashing when parsing the updated values (cast from `int` to `uint32`).

### Steps to Reproduce

1. `terraform apply`
2. Change integer values of `min_scale` and/or `max_scale` arguments in `scaleway_container.default`
3. `terraform apply`

**Comment by Monitob** [comment]
Hello @rclement, Thanks for the report. Fix is coming soon
