### ISSUE TITLE
GRPC Provider failing for scaleway_rdb_privilege, scaleway_rdb_instance and scaleway_instance_server

### ISSUE THREAD

**Issue by eviscares** [scaleway/terraform-provider-scaleway#1437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.2.7
on darwin_arm64
+ provider registry.terraform.io/1password/onepassword v1.1.4
+ provider registry.terraform.io/grafana/grafana v1.27.0
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/scaleway/scaleway v2.2.7

### Affected Resource(s)

* scaleway_rdb_privileges

### Terraform Configuration Files
This is exemplary for the multiple elements which fail.

#### scaleway_rdb_privilege
```hcl
resource "scaleway_rdb_privilege" "connect" {
  depends_on    = [scaleway_rdb_user.connect] 
  instance_id   = module.postgres.rdb_id
  user_name     = scaleway_rdb_user.connect.name
  database_name = scaleway_rdb_database.connect.name
  permission    = "all"
}
```
#### scaleway_rdb_instance
```hcl
resource "scaleway_instance_server" "bastion" {
  depends_on = [scaleway_account_ssh_key.bastion]

  name  = "bastion-${var.env_id}"
  type  = var.bastion_server_size
  image = "ubuntu_focal"

  security_group_id = scaleway_instance_security_group.bastion.id
  ip_id             = scaleway_instance_ip.bastion.id

  tags = ["bastion", var.env_id]

  user_data = {
    cloud-init = templatefile("${path.module}/cloud-init.sh", {
      PGHOST     = var.pg_ip
      PGPORT     = var.pg_port
      PGUSER     = scaleway_rdb_user.bastion.name
      PGDATABASE = var.bastion_accessible_dbs[0]
    })
  }
```

#### scaleway_instance_server
```hcl
data "scaleway_instance_server" "one_k8s_node" {
  name = scaleway_k8s_pool.pool.nodes[0].name
}
```

### Debug Output
```
module.postgres.random_password.admin: Refreshing state... [id=none]
random_password.keycloak_user: Refreshing state... [id=none]
random_password.connect_user: Refreshing state... [id=none]
module.bastion.random_password.bastion: Refreshing state... [id=none]
random_password.big_data_user: Refreshing state... [id=none]
module.promtail.data.onepassword_item.loki_access: Reading...
module.prometheus_agent.data.onepassword_item.prometheus_access: Reading...
scaleway_registry_namespace.perma: Refreshing state... [id=nl-ams/1196aaac-0875-40fd-bfdb-9acfd29b047d]
module.bastion.scaleway_account_ssh_key.bastion: Refreshing state... [id=cbc82b2e-9bab-488c-a1cb-1378f486c880]
module.kubernetes.scaleway_lb_ip.nginx_ip: Refreshing state... [id=nl-ams-1/6381bb11-587b-4d76-97ba-1efbdfb07a09]
module.bastion.scaleway_instance_ip.bastion: Refreshing state... [id=nl-ams-1/c7bb269d-376b-40c4-bd05-75b32c4cd8c0]
module.object_storage.scaleway_object_bucket.img_s3_bucket: Refreshing state... [id=nl-ams/perma-images-prod]
module.bastion.scaleway_instance_security_group.bastion: Refreshing state... [id=nl-ams-1/8a44174a-d36a-4153-8fea-c9d59789db66]
module.kubernetes.scaleway_k8s_cluster.perma: Refreshing state... [id=nl-ams/122d03ca-625d-47eb-87d3-2dc39a7624ba]
module.postgres.scaleway_rdb_instance.rdb: Refreshing state... [id=nl-ams/9fe65482-cf4d-4ee3-b42c-59364898d26d]
module.promtail.data.onepassword_item.loki_access: Read complete after 0s [id=vaults/cld3k6uurrg2zn4dpaeueeagua/items/zl34jboa7lsbaiw7hgvckgnq6i]
module.prometheus_agent.data.onepassword_item.prometheus_access: Read complete after 0s [id=vaults/cld3k6uurrg2zn4dpaeueeagua/items/qmhpjwtxp5zjwvwdy3rulpdgli]
module.kubernetes.scaleway_domain_record.a_record[2]: Refreshing state... [id=10ba685d-52e3-4bad-b01a-32161cd57ca3]
module.kubernetes.scaleway_domain_record.a_record[0]: Refreshing state... [id=6eb16bfa-39ae-4491-a24a-eb5219c6f90f]
module.kubernetes.scaleway_domain_record.a_record[1]: Refreshing state... [id=699b3e3e-574f-4e51-8c1b-bfc24893742d]
module.kubernetes.scaleway_k8s_pool.pool: Refreshing state... [id=nl-ams/c3d1df91-f70f-48f6-b5d7-83f026392212]
scaleway_rdb_database.connect: Refreshing state... [id=nl-ams/9fe65482-cf4d-4ee3-b42c-59364898d26d/connect-prod]
scaleway_rdb_user.big_data: Refreshing state... [id=nl-ams/9fe65482-cf4d-4ee3-b42c-59364898d26d/big_data]
module.bastion.data.scaleway_rdb_instance.rdb: Reading...
scaleway_rdb_user.keycloak: Refreshing state... [id=nl-ams/9fe65482-cf4d-4ee3-b42c-59364898d26d/keycloak]
scaleway_rdb_user.connect: Refreshing state... [id=nl-ams/9fe65482-cf4d-4ee3-b42c-59364898d26d/connect]
module.bastion.scaleway_rdb_user.bastion: Refreshing state... [id=nl-ams/9fe65482-cf4d-4ee3-b42c-59364898d26d/bastion]
scaleway_rdb_database.keycloak: Refreshing state... [id=nl-ams/9fe65482-cf4d-4ee3-b42c-59364898d26d/keycloak-prod]
module.kubernetes.data.scaleway_instance_server.one_k8s_node: Reading...
module.kubernetes.null_resource.kubeconfig: Refreshing state... [id=6689477304239786414]
module.postgres.scaleway_rdb_acl.main: Refreshing state... [id=nl-ams/9fe65482-cf4d-4ee3-b42c-59364898d26d]
module.kubernetes.local_file.kubeconfig: Refreshing state... [id=91798a6907905cf0a91bde44c6e8a2649f476bca]
module.kubernetes.helm_release.nginx_ingress: Refreshing state... [id=nginx-ingress]
module.bastion.data.scaleway_rdb_instance.rdb: Read complete after 0s [id=nl-ams/9fe65482-cf4d-4ee3-b42c-59364898d26d]
scaleway_rdb_privilege.keycloak: Refreshing state... [id=nl-ams/9fe65482-cf4d-4ee3-b42c-59364898d26d]
kubernetes_secret_v1.keycloak_user_credentials: Refreshing state... [id=default/keycloak-db-user-credentials]
kubernetes_secret_v1.mlp_db_credentials: Refreshing state... [id=default/mlp-db-access-db-user-credentials]
kubernetes_secret_v1.docker_cfg: Refreshing state... [id=default/docker-cfg]
kubernetes_secret_v1.mlp_db_id_rsa: Refreshing state... [id=default/mlp-db-access-id-rsa]
scaleway_rdb_privilege.connect: Refreshing state... [id=nl-ams/9fe65482-cf4d-4ee3-b42c-59364898d26d]
kubernetes_secret_v1.connect_user_credentials: Refreshing state... [id=default/connect-db-user-credentials]
module.object_storage.kubernetes_secret_v1.object_storage_access: Refreshing state... [id=default/object-storage-access]
module.object_storage.helm_release.img_proxy: Refreshing state... [id=imgproxy]
module.kubernetes.helm_release.jetstack-cert-manager: Refreshing state... [id=cert-manager]
module.object_storage.kubernetes_config_map_v1.img_proxy_host: Refreshing state... [id=default/img-proxy-host]
╷
│ Warning: Deprecated attribute
│
│   on ../modules/postgres/outputs.tf line 2, in output "pg_ip":
│    2:   value = scaleway_rdb_instance.rdb.endpoint_ip
│
│ The attribute "endpoint_ip" is deprecated. Refer to the provider documentation for details.
│
│ (and 3 more similar warnings elsewhere)
╵
╷
│ Error: Plugin did not respond
│
│   with scaleway_rdb_privilege.connect,
│   on database.tf line 23, in resource "scaleway_rdb_privilege" "connect":
│   23: resource "scaleway_rdb_privilege" "connect" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with scaleway_rdb_privilege.keycloak,
│   on database.tf line 52, in resource "scaleway_rdb_privilege" "keycloak":
│   52: resource "scaleway_rdb_privilege" "keycloak" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│   with scaleway_rdb_privilege.big_data_connect,
│   on database.tf line 77, in resource "scaleway_rdb_privilege" "big_data_connect":
│   77: resource "scaleway_rdb_privilege" "big_data_connect" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with module.bastion.scaleway_rdb_privilege.bastion[0],
│   on ../modules/bastion/db_users.tf line 16, in resource "scaleway_rdb_privilege" "bastion":
│   16: resource "scaleway_rdb_privilege" "bastion" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with module.bastion.scaleway_rdb_privilege.bastion[1],
│   on ../modules/bastion/db_users.tf line 16, in resource "scaleway_rdb_privilege" "bastion":
│   16: resource "scaleway_rdb_privilege" "bastion" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with module.bastion.scaleway_instance_server.bastion,
│   on ../modules/bastion/main.tf line 18, in resource "scaleway_instance_server" "bastion":
│   18: resource "scaleway_instance_server" "bastion" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│   with module.kubernetes.data.scaleway_instance_server.one_k8s_node,
│   on ../modules/kubernetes/k8s_cluster.tf line 26, in data "scaleway_instance_server" "one_k8s_node":
│   26: data "scaleway_instance_server" "one_k8s_node" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.postgres.scaleway_rdb_acl.main,
│   on ../modules/postgres/main.tf line 24, in resource "scaleway_rdb_acl" "main":
│   24: resource "scaleway_rdb_acl" "main" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
```
### Panic Output
```
Stack trace from the terraform-provider-scaleway_v2.2.7 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1057a5640]

goroutine 328 [running]:
github.com/scaleway/terraform-provider-scaleway/v2/scaleway.rdbACLRulesFlattenFromSchema({0x14000a894a0, 0x7, 0x9}, {0x14000532180, 0x6, 0x6})
	github.com/scaleway/terraform-provider-scaleway/v2/scaleway/resource_rdb_acl.go:255 +0x4d0
github.com/scaleway/terraform-provider-scaleway/v2/scaleway.resourceScalewayRdbACLRead({0x105cbd448, 0x140005ef6e0}, 0x14000746a80, {0x105b08f40, 0x14000b011b0})
	github.com/scaleway/terraform-provider-scaleway/v2/scaleway/resource_rdb_acl.go:129 +0x478
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x140001967e0, {0x105cbd480, 0x14000544180}, 0x14000746a80, {0x105b08f40, 0x14000b011b0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:724 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140001967e0, {0x105cbd480, 0x14000544180}, 0x140008f5380, {0x105b08f40, 0x14000b011b0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:1015 +0x548
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000117a10, {0x105cbd480, 0x14000da7fb0}, 0x1400071a900)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:613 +0x658
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140007a7540, {0x105cbd480, 0x14000da79b0}, 0x140005ee720)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/tf5server/server.go:747 +0x474
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x105c52a00, 0x140007a7540}, {0x105cbd480, 0x14000da79b0}, 0x140003762a0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400012e8c0, {0x105ccda50, 0x140007829c0}, 0x14000b37e60, 0x140003a0f30, 0x106395610, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb50
google.golang.org/grpc.(*Server).handleStream(0x1400012e8c0, {0x105ccda50, 0x140007829c0}, 0x14000b37e60, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400028a570, 0x1400012e8c0, {0x105ccda50, 0x140007829c0}, 0x14000b37e60)
	google.golang.org/grpc@v1.48.0/server.go:932 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x1f0

Error: The terraform-provider-scaleway_v2.2.7 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

`terraform plan` should analyze the steps neccesary for the environment.

### Actual Behavior

See above

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

It is not related to the deprecated `endpoint_ip` attribute. Refactoring around that didn't help.

### References

* #0000

**Comment by Monitob** [comment]
Hello @eviscares, Thank you for the bug report. Can I have a snippet of your resource `scaleway_rdb_acl`? You can also join me via Community Slack for further questions.

**Comment by Monitob** [comment]
I am not enabled to reproduce your issue but I enhance the ACL setter

**Comment by Monitob** [comment]
I've noted also that you are using `endpoint_ip` which is deprecated. Please use the `privat_network` attribute. If you are trying to connect to a bastion please should not use the `ip_id` attribute on the `scaleway_instance_server`. You should only use the `private_network` or the `scaleway_instance_private_nic`. You are going to find the IP address on your DHCP server config dynamically created.

**Comment by eviscares** [comment]
Hi,

thanks for taking a look at this. I already tried it with using the `private_network`, but that did noth change anything.
Here's one of the `scaleway_rdb_acl` it failed on:
```hcl
resource "scaleway_rdb_acl" "main" {
  depends_on  = [var.kubernetes_pool]
  instance_id = scaleway_rdb_instance.rdb.id

  # for future use (SSH access to database)

  acl_rules {
    ip          = "${var.bastion_ip}/32"
    description = "Bastion IP"
  }

  # Add each kubernetes node IP to the access list so they can use the database
  dynamic "acl_rules" {
    for_each = var.kubernetes_pool.nodes
    content {
      ip          = "${acl_rules.value["public_ip"]}/32"
      description = "IP of Cluster Node ${acl_rules.value["name"]}"
    }
  }

  dynamic "acl_rules" {
    for_each = local.vpn_ips
    content {
      ip          = acl_rules.value
      description = "VPN IP"
    }
  }

  dynamic "acl_rules" {
    for_each = local.wan_ips
    content {
      ip          = acl_rules.value
      description = "WAN"
    }
  }
```

**Comment by Monitob** [comment]
We found the issue, It will be fixed soon. It was related to an update on the ACL rules. Thanks for the report.

**Comment by eviscares** [comment]
You're very much welcome.
Thanks for taking care.
